# -*- coding: utf-8 -*-
"""imagenet-mla100

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1SQmeZHWq5q5Iy7GYF6nnJhxxi0E4t6Wj

# Reports
"""

!pip -q install reportlab

from __future__ import annotations

import json
import math
import os
from dataclasses import dataclass
from pathlib import Path
from typing import Any, Callable, Dict, List, Optional, Sequence, Tuple

import numpy as np
import torch
import torch.nn.functional as F
import matplotlib.pyplot as plt

from sklearn.metrics import confusion_matrix, classification_report

from reportlab.lib.pagesizes import letter
from reportlab.lib.styles import getSampleStyleSheet
from reportlab.lib.units import inch
from reportlab.platypus import (
    SimpleDocTemplate,
    Paragraph,
    Spacer,
    Image as RLImage,
    PageBreak,
    Table,
    TableStyle,
)
from reportlab.lib import colors


# ----------------------------
# Config
# ----------------------------
@dataclass
class ReportConfig:
    run_name: str = "run"
    out_dir: str = "artifacts"
    num_classes: int = 20
    class_names: Optional[List[str]] = None  # length=num_classes if provided
    top_k_examples: int = 12                  # number of high-value mistakes to render
    max_batches: Optional[int] = None         # None = full val set; otherwise limit for fast runs
    dpi: int = 200
    input_is_normalized_0_1: bool = True      # if your tensors are already [0,1]
    make_pdf_each_epoch: bool = True          # set False if you only want images + JSON


# ----------------------------
# Utilities
# ----------------------------
def _ensure_dir(p: Path) -> None:
    p.mkdir(parents=True, exist_ok=True)

def _to_numpy(x: torch.Tensor) -> np.ndarray:
    return x.detach().cpu().numpy()

def _safe_class_name(i: int, cfg: ReportConfig) -> str:
    if cfg.class_names and 0 <= i < len(cfg.class_names):
        return cfg.class_names[i]
    return str(i)

def _denorm_to_01(img: torch.Tensor) -> torch.Tensor:
    # If user already provides [0,1], do nothing.
    # If not, clamp to [0,1] to avoid ugly plots.
    return img.clamp(0, 1)

def _save_image_png(img_chw_01: torch.Tensor, out_path: Path, dpi: int) -> None:
    img = _denorm_to_01(img_chw_01).permute(1, 2, 0).detach().cpu().numpy()
    plt.figure()
    plt.imshow(img)
    plt.axis("off")
    plt.tight_layout(pad=0)
    plt.savefig(out_path, dpi=dpi, bbox_inches="tight", pad_inches=0)
    plt.close()

def _save_cam_overlay_png(img_chw_01: torch.Tensor, cam_hw_01: np.ndarray, out_path: Path, dpi: int) -> None:
    img = _denorm_to_01(img_chw_01).permute(1, 2, 0).detach().cpu().numpy()
    cam = np.clip(cam_hw_01, 0.0, 1.0)

    plt.figure()
    plt.imshow(img)
    plt.imshow(cam, alpha=0.45)  # overlay heatmap
    plt.axis("off")
    plt.tight_layout(pad=0)
    plt.savefig(out_path, dpi=dpi, bbox_inches="tight", pad_inches=0)
    plt.close()

def _plot_confusion_matrix(cm: np.ndarray, cfg: ReportConfig, out_path: Path) -> None:
    plt.figure(figsize=(8, 7))
    plt.imshow(cm)
    plt.title("Confusion Matrix")
    plt.xlabel("Predicted")
    plt.ylabel("True")
    plt.colorbar()
    plt.tight_layout()
    plt.savefig(out_path, dpi=cfg.dpi)
    plt.close()

def _plot_worst_classes(per_class_f1: np.ndarray, cfg: ReportConfig, out_path: Path, k: int = 8) -> None:
    k = min(k, cfg.num_classes)
    idx = np.argsort(per_class_f1)[:k]
    labels = [_safe_class_name(int(i), cfg) for i in idx]
    vals = per_class_f1[idx]

    plt.figure(figsize=(9, 4))
    plt.bar(range(k), vals)
    plt.xticks(range(k), labels, rotation=30, ha="right")
    plt.ylim(0, 1)
    plt.title(f"Worst {k} Classes by F1")
    plt.ylabel("F1")
    plt.tight_layout()
    plt.savefig(out_path, dpi=cfg.dpi)
    plt.close()

def _softmax_np(logits: np.ndarray) -> np.ndarray:
    logits = logits - logits.max(axis=1, keepdims=True)
    exp = np.exp(logits)
    return exp / (exp.sum(axis=1, keepdims=True) + 1e-12)


# ----------------------------
# Default Grad-CAM for your SimpleDNN
# Matches your current model structure:
#   features -> classifier(conv1x1) -> global_pool -> logits
# (mirrors get_gradcam(...) in your script) :contentReference[oaicite:3]{index=3}
# ----------------------------
def default_gradcam_simplednn(model: torch.nn.Module, image_chw: torch.Tensor, target_class: int) -> np.ndarray:
    model.eval()

    if image_chw.dim() == 3:
        image = image_chw.unsqueeze(0)
    else:
        image = image_chw

    image = image.to(next(model.parameters()).device)

    # Forward through feature extractor
    features = model.features(image)
    features.requires_grad_(True)
    features.retain_grad()

    # Manual forward head
    x = model.classifier(features)
    x = model.global_pool(x)
    logits = x.squeeze(3).squeeze(2)

    model.zero_grad(set_to_none=True)
    logits[0, int(target_class)].backward()

    grads = features.grad.mean(dim=[2, 3], keepdim=True)
    cam = (grads * features).sum(dim=1).squeeze()
    cam = F.relu(cam)

    cam = cam.detach().cpu().numpy()
    cam = cam - cam.min()
    cam = cam / (cam.max() + 1e-7)
    return cam


# ----------------------------
# Reporter
# ----------------------------
class ModelReporter:
    def __init__(
        self,
        cfg: ReportConfig,
        gradcam_fn: Optional[Callable[[torch.nn.Module, torch.Tensor, int], np.ndarray]] = None,
    ) -> None:
        self.cfg = cfg
        self.gradcam_fn = gradcam_fn  # can be None to skip cams

        self.root = Path(cfg.out_dir) / cfg.run_name
        _ensure_dir(self.root)

    @torch.no_grad()
    def evaluate(
        self,
        model: torch.nn.Module,
        val_loader: torch.utils.data.DataLoader,
        device: torch.device,
        criterion: Optional[torch.nn.Module] = None,
    ) -> Dict[str, Any]:
        model.eval()

        all_true: List[int] = []
        all_pred: List[int] = []
        all_logits: List[np.ndarray] = []
        all_files: List[str] = []
        all_imgs: List[torch.Tensor] = []  # store CPU CHW tensors for selected examples later

        total_loss = 0.0
        total = 0

        for b, batch in enumerate(val_loader):
            if self.cfg.max_batches is not None and b >= self.cfg.max_batches:
                break

            # Support either (images, labels) or (images, labels, filenames)
            if len(batch) == 2:
                images, labels = batch
                filenames = [f"sample_{total+i:06d}" for i in range(images.size(0))]
            else:
                images, labels, filenames = batch
                filenames = list(filenames)

            images = images.to(device)
            labels = labels.to(device)

            logits = model(images)

            if criterion is not None:
                loss = criterion(logits, labels).item()
                total_loss += loss

            pred = logits.argmax(dim=1)

            bs = labels.size(0)
            total += bs

            all_true.extend(labels.detach().cpu().tolist())
            all_pred.extend(pred.detach().cpu().tolist())
            all_logits.append(_to_numpy(logits))

            # keep filenames + raw images on CPU for later rendering of examples
            all_files.extend([str(x) for x in filenames])
            all_imgs.extend([img.detach().cpu() for img in images.detach().cpu()])

        logits_np = np.concatenate(all_logits, axis=0) if all_logits else np.zeros((0, self.cfg.num_classes), dtype=np.float32)
        probs_np = _softmax_np(logits_np) if logits_np.shape[0] > 0 else logits_np

        cm = confusion_matrix(all_true, all_pred, labels=list(range(self.cfg.num_classes)))
        report_dict = classification_report(
            all_true,
            all_pred,
            labels=list(range(self.cfg.num_classes)),
            output_dict=True,
            zero_division=0,
        )

        # Extract per-class F1
        per_class_f1 = np.zeros((self.cfg.num_classes,), dtype=np.float32)
        for i in range(self.cfg.num_classes):
            per_class_f1[i] = float(report_dict.get(str(i), {}).get("f1-score", 0.0))

        acc = float((np.array(all_true) == np.array(all_pred)).mean()) if total > 0 else 0.0
        avg_loss = float(total_loss / max(1, (b + 1))) if criterion is not None else float("nan")

        return {
            "loss": avg_loss,
            "acc": acc,
            "true": np.array(all_true, dtype=np.int64),
            "pred": np.array(all_pred, dtype=np.int64),
            "logits": logits_np,
            "probs": probs_np,
            "filenames": all_files,
            "images_cpu": all_imgs,  # list of CHW tensors
            "confusion_matrix": cm,
            "classification_report": report_dict,
            "per_class_f1": per_class_f1,
        }

    def _select_top_mistakes(self, eval_out: Dict[str, Any]) -> List[int]:
        true = eval_out["true"]
        pred = eval_out["pred"]
        probs = eval_out["probs"]

        wrong = np.where(true != pred)[0]
        if wrong.size == 0:
            return []

        # "High-value mistakes" = high confidence but wrong
        conf = probs[wrong, pred[wrong]]
        order = np.argsort(-conf)  # descending
        top = wrong[order][: self.cfg.top_k_examples]
        return top.tolist()

    def build_epoch_report(
        self,
        model: torch.nn.Module,
        val_loader: torch.utils.data.DataLoader,
        device: torch.device,
        epoch: int,
        criterion: Optional[torch.nn.Module] = None,
        extra_meta: Optional[Dict[str, Any]] = None,
    ) -> Path:
        """
        Generates images + JSON + optional PDF for a given epoch.
        Returns the path to the PDF if generated, otherwise returns the epoch dir path.
        """
        cfg = self.cfg
        epoch_dir = self.root / f"epoch_{epoch:03d}"
        ex_dir = epoch_dir / "examples"
        _ensure_dir(epoch_dir)
        _ensure_dir(ex_dir)

        eval_out = self.evaluate(model, val_loader, device=device, criterion=criterion)

        # --- Plots
        cm_path = epoch_dir / "confusion_matrix.png"
        worst_path = epoch_dir / "worst_classes.png"
        _plot_confusion_matrix(eval_out["confusion_matrix"], cfg, cm_path)
        _plot_worst_classes(eval_out["per_class_f1"], cfg, worst_path, k=min(8, cfg.num_classes))

        # --- Example rendering (image + gradcam overlay)
        top_idx = self._select_top_mistakes(eval_out)
        examples: List[Dict[str, Any]] = []
        for rank, i in enumerate(top_idx):
            img = eval_out["images_cpu"][i]
            t = int(eval_out["true"][i])
            p = int(eval_out["pred"][i])
            fname = eval_out["filenames"][i]
            conf = float(eval_out["probs"][i, p])

            img_path = ex_dir / f"{rank:02d}_img.png"
            cam_path = ex_dir / f"{rank:02d}_cam.png"

            _save_image_png(img, img_path, cfg.dpi)

            cam_saved = False
            if self.gradcam_fn is not None:
                # Grad-CAM requires gradients -> run with grad enabled
                cam = self.gradcam_fn(model, img, p)
                _save_cam_overlay_png(img, cam, cam_path, cfg.dpi)
                cam_saved = True

            examples.append({
                "rank": rank,
                "index": int(i),
                "file": fname,
                "true": t,
                "pred": p,
                "true_name": _safe_class_name(t, cfg),
                "pred_name": _safe_class_name(p, cfg),
                "conf": conf,
                "img_path": str(img_path),
                "cam_path": str(cam_path) if cam_saved else None,
            })

        # --- JSON artifact (easy to diff / compare runs)
        meta = {
            "epoch": int(epoch),
            "num_classes": int(cfg.num_classes),
            "class_names": cfg.class_names,
            "loss": float(eval_out["loss"]) if not math.isnan(eval_out["loss"]) else None,
            "acc": float(eval_out["acc"]),
        }
        if extra_meta:
            meta.update(extra_meta)

        report_json = {
            "meta": meta,
            "plots": {
                "confusion_matrix": str(cm_path),
                "worst_classes": str(worst_path),
            },
            "examples": examples,
            "classification_report": eval_out["classification_report"],
        }

        json_path = epoch_dir / "report_data.json"
        with open(json_path, "w") as f:
            json.dump(report_json, f, indent=2)

        # --- Optional PDF
        if cfg.make_pdf_each_epoch:
            pdf_path = epoch_dir / f"report_epoch_{epoch:03d}.pdf"
            self._build_pdf(report_json, pdf_path)
            return pdf_path

        return epoch_dir

    def _build_pdf(self, report_json: Dict[str, Any], pdf_path: Path) -> None:
        styles = getSampleStyleSheet()
        doc = SimpleDocTemplate(str(pdf_path), pagesize=letter)
        story: List[Any] = []

        meta = report_json["meta"]
        plots = report_json["plots"]
        examples = report_json.get("examples", [])

        # Title + summary
        story.append(Paragraph("Model Evaluation Report", styles["Title"]))
        story.append(Spacer(1, 0.15 * inch))

        acc = meta.get("acc", 0.0)
        loss = meta.get("loss", None)
        line = f"Epoch: {meta.get('epoch')} &nbsp;&nbsp; Acc: {acc*100:.2f}%"
        if loss is not None:
            line += f" &nbsp;&nbsp; Loss: {loss:.4f}"
        story.append(Paragraph(line, styles["Normal"]))
        story.append(Spacer(1, 0.15 * inch))

        # Add plots
        for key in ["confusion_matrix", "worst_classes"]:
            p = plots.get(key)
            if p and os.path.exists(p):
                story.append(Paragraph(key.replace("_", " ").title(), styles["Heading2"]))
                story.append(Spacer(1, 0.08 * inch))
                story.append(RLImage(p, width=6.6 * inch, height=4.8 * inch))
                story.append(Spacer(1, 0.2 * inch))

        story.append(PageBreak())

        # Classification report table (compact: per-class F1 + support)
        story.append(Paragraph("Per-Class Summary", styles["Heading1"]))
        story.append(Spacer(1, 0.12 * inch))

        cr = report_json.get("classification_report", {})
        rows = [["Class", "Precision", "Recall", "F1", "Support"]]
        num_classes = int(meta.get("num_classes", 0))
        for i in range(num_classes):
            c = cr.get(str(i), {})
            rows.append([
                _safe_class_name(i, self.cfg),
                f"{c.get('precision', 0.0):.3f}",
                f"{c.get('recall', 0.0):.3f}",
                f"{c.get('f1-score', 0.0):.3f}",
                str(int(c.get('support', 0))),
            ])

        tbl = Table(rows, hAlign="LEFT", colWidths=[1.2*inch, 1.0*inch, 1.0*inch, 0.8*inch, 0.8*inch])
        tbl.setStyle(TableStyle([
            ("BACKGROUND", (0,0), (-1,0), colors.lightgrey),
            ("GRID", (0,0), (-1,-1), 0.25, colors.grey),
            ("FONTNAME", (0,0), (-1,0), "Helvetica-Bold"),
            ("FONTSIZE", (0,0), (-1,-1), 8),
            ("ALIGN", (1,1), (-1,-1), "RIGHT"),
        ]))
        story.append(tbl)
        story.append(PageBreak())

        # Example panels
        story.append(Paragraph("High-Confidence Mistakes (Examples)", styles["Heading1"]))
        story.append(Spacer(1, 0.12 * inch))

        for ex in examples:
            title = (
                f"{ex.get('file','')}"
                f" — True: {ex.get('true_name')}  |  Pred: {ex.get('pred_name')}"
                f"  (conf {ex.get('conf',0.0):.2f})"
            )
            story.append(Paragraph(title, styles["Normal"]))
            story.append(Spacer(1, 0.06 * inch))

            imgp = ex.get("img_path")
            camp = ex.get("cam_path")

            # Side-by-side images if cam exists; otherwise just raw image
            if imgp and os.path.exists(imgp) and camp and os.path.exists(camp):
                row = [[RLImage(imgp, width=3.2*inch, height=3.2*inch),
                        RLImage(camp, width=3.2*inch, height=3.2*inch)]]
                story.append(Table(row, colWidths=[3.3*inch, 3.3*inch]))
            elif imgp and os.path.exists(imgp):
                story.append(RLImage(imgp, width=4.2*inch, height=4.2*inch))

            story.append(Spacer(1, 0.18 * inch))

        doc.build(story)

"""# ImageNet Classification for the MLA100 NPU chip

## Load Dataset
"""

!cp /content/drive/MyDrive/NPULab/spring-2026-data/imagenet_train20.txt imagenet_train20.txt
!cp /content/drive/MyDrive/NPULab/spring-2026-data/imagenet_val20.txt imagenet_val20.txt

# Text contains:
# file class_number
# file2 class_number2
# ...

!cp /content/drive/MyDrive/NPULab/spring-2026-data/imagenet_train20.zip imagenet_train20.zip

!cp /content/drive/MyDrive/NPULab/spring-2026-data/imagenet_val20.zip imagenet_val20.zip

!unzip -o -q imagenet_train20.zip
#   inflating: imagenet_train20a/n04346328/n04346328_2302.JPEG
#  inflating: imagenet_train20a/n04346328/n04346328_2842.JPEG

!unzip -o -q imagenet_val20.zip
# NOT NESTED UNDER SUB FOLDERS LIKE TRAINING
# ex., we get
# /imagenet_val20/n01737021_10767.JPEG

"""## Install Requirements"""

!pip -q install onnxscript onnxruntime

# Import required libraries
import torch
import torch.nn as nn
import torch.optim as optim
import torch.onnx
from torch.utils.data import Dataset, DataLoader
from torchvision import transforms
from PIL import Image
import os
import onnxscript
import onnxruntime as ort
import torch.nn.functional as F
from sklearn.metrics import classification_report, confusion_matrix
import numpy as np
import matplotlib.pyplot as plt

"""## Prepare Dataset Loader"""

IMAGE_ROOT = 'imagenet_train20a'
TRAIN_LIST = 'imagenet_train20.txt'
VAL_IMAGE_ROOT = 'imagenet_val20'
VAL_LIST = 'imagenet_val20.txt'
BATCH_SIZE = 32
NUM_CLASSES = 20
INPUT_SHAPE = (240, 240)
NUM_EPOCHS = 10
LEARNING_RATE = 0.01

class ImageNet20Dataset(Dataset):
    def __init__(self, txt_file, root_dir, transform=None):
        self.img_labels = []
        self.root_dir = root_dir
        self.transform = transform
        with open(txt_file, 'r') as f:
            for line in f:
                parts = line.strip().split()
                if len(parts) >= 2:
                    self.img_labels.append((parts[0], int(parts[1])))

    def __len__(self):
        return len(self.img_labels)

    def __getitem__(self, idx):
        filename, label = self.img_labels[idx]

        path_flat = os.path.join(self.root_dir, filename)
        path_nested = os.path.join(self.root_dir, filename.split('_')[0], filename)
        full_path = path_flat if os.path.exists(path_flat) else path_nested

        try:
            image = Image.open(full_path).convert("RGB")
        except Exception:
            image = Image.new('RGB', (240, 240)) # Fallback if both fail

        if self.transform: image = self.transform(image)
        return image, label

"""## Prepare SimpleDNN"""

import torch
import torch.nn as nn

class NPUModel(nn.Module):
    def __init__(self, num_classes=20):
        super(NPUModel, self).__init__()

        # -----------------------------------------------------------------
        # STAGE 1: STEM (EfficientNetV2 Style)
        # Fast downsampling using a dense Fused-Convolution.
        # -----------------------------------------------------------------
        # Input: (3, H, W) -> Output: (32, H/2, W/2)
        self.stem = nn.Sequential(
            nn.Conv2d(
                in_channels=3,
                out_channels=32,
                kernel_size=3,
                stride=2,
                padding=1,
                bias=False  # Bias handled by BN
            ),
            nn.BatchNorm2d(32),
            nn.ReLU(inplace=True)
        )

        # -----------------------------------------------------------------
        # STAGE 2: FUSED-MBCONV BLOCK (EfficientNetV2)
        # High FLOPs utilization. We expand, conv, and project.
        # -----------------------------------------------------------------
        # Input: (32, H/2, W/2) -> Output: (64, H/4, W/4)
        self.stage2 = nn.Sequential(
            # Fused Expansion + Downsampling
            nn.Conv2d(
                in_channels=32,
                out_channels=64 * 4, # Expand ratio 4
                kernel_size=3,
                stride=2,            # Downsample here
                padding=1,
                bias=False
            ),
            nn.BatchNorm2d(64 * 4),
            nn.ReLU(inplace=True),

            # Projection (1x1)
            nn.Conv2d(
                in_channels=64 * 4,
                out_channels=64,
                kernel_size=1,
                stride=1,
                padding=0,
                bias=False
            ),
            nn.BatchNorm2d(64)
        )

        # -----------------------------------------------------------------
        # STAGE 3: FASTERNET BLOCK (PConv)
        # Low Latency. Only convolves 1/4 of channels.
        # -----------------------------------------------------------------
        # Input: (64, H/4, W/4) -> Output: (128, H/8, W/8)
        self.stage3_downsample = nn.Sequential(
             nn.Conv2d(64, 128, kernel_size=3, stride=2, padding=1, bias=False),
             nn.BatchNorm2d(128),
             nn.ReLU(inplace=True)
        )

        # The PConv Block
        self.stage3_pconv = PConvBlock(dim=128, n_div=4)

        # -----------------------------------------------------------------
        # STAGE 4: CONVNEXT / MOBILENETV3 STYLE BLOCK
        # Depthwise Separable Conv for feature refinement.
        # -----------------------------------------------------------------
        # Input: (128, H/8, W/8) -> Output: (256, H/16, W/16)
        self.stage4 = nn.Sequential(
            # 1. Pointwise Expansion
            nn.Conv2d(128, 256, kernel_size=1, stride=1, padding=0, bias=False),
            nn.BatchNorm2d(256),
            nn.ReLU(inplace=True),

            # 2. Depthwise Conv (Spatial mixing) - Stride 2 for downsample
            nn.Conv2d(
                256,
                256,
                kernel_size=3, # Or 5x5/7x7 if NPU supports large kernels
                stride=2,
                padding=1,
                groups=256,    # Depthwise
                bias=False
            ),
            nn.BatchNorm2d(256),
            nn.ReLU(inplace=True),

            # 3. Pointwise Projection
            nn.Conv2d(256, 256, kernel_size=1, stride=1, padding=0, bias=False),
            nn.BatchNorm2d(256)
        )

        # -----------------------------------------------------------------
        # CLASSIFIER HEAD
        # Fully Convolutional (Linear replaced by Conv2d as requested)
        # -----------------------------------------------------------------
        self.classifier_conv = nn.Conv2d(
            in_channels=256,
            out_channels=num_classes,
            kernel_size=1,
            stride=1,
            padding=0,
            bias=True # True here as it's the final layer (no BN following)
        )

        self.global_pool = nn.AdaptiveAvgPool2d((1, 1))

    def forward(self, x):
        # x: (N, 3, 240, 240)
        x = self.stem(x)         # -> (N, 32, 120, 120)
        x = self.stage2(x)       # -> (N, 64, 60, 60)

        x = self.stage3_downsample(x) # -> (N, 128, 30, 30)
        x = self.stage3_pconv(x)      # -> (N, 128, 30, 30)

        x = self.stage4(x)       # -> (N, 256, 15, 15)

        # Classification Head
        x = self.classifier_conv(x) # -> (N, 20, 15, 15)
        x = self.global_pool(x)     # -> (N, 20, 1, 1)
        x = x.squeeze(3).squeeze(2) # -> (N, 20)
        return x


class PConvBlock(nn.Module):
    """
    FasterNet Partial Convolution Block.
    Applies Conv only to a split of the channels to save FLOPs.
    """
    def __init__(self, dim, n_div=4):
        super(PConvBlock, self).__init__()
        self.dim_conv3 = dim // n_div
        self.dim_untouched = dim - self.dim_conv3

        # Partial Convolution: Only affects 1/4th of channels
        self.partial_conv = nn.Conv2d(
            in_channels=self.dim_conv3,
            out_channels=self.dim_conv3,
            kernel_size=3,
            stride=1,
            padding=1,
            bias=False
        )
        self.bn = nn.BatchNorm2d(self.dim_conv3)
        self.relu = nn.ReLU(inplace=True)

        # Pointwise Mixer (1x1) to mix information across all channels
        self.pw_conv = nn.Conv2d(
            in_channels=dim,
            out_channels=dim,
            kernel_size=1,
            stride=1,
            padding=0,
            bias=False
        )
        self.bn_pw = nn.BatchNorm2d(dim)
        self.relu_pw = nn.ReLU(inplace=True)

    def forward(self, x):
        # Slicing for PConv (FasterNet)
        # Note: If NPU does not support slicing, standard Group Conv is the fallback.
        x1 = x[:, :self.dim_conv3, :, :]
        x2 = x[:, self.dim_conv3:, :, :]

        x1 = self.partial_conv(x1)
        x1 = self.bn(x1)
        x1 = self.relu(x1)

        # Concatenate back
        x = torch.cat((x1, x2), dim=1)

        # Pointwise mixing
        x = self.pw_conv(x)
        x = self.bn_pw(x)
        x = self.relu_pw(x)

        return x

"""## Data Augmentations"""

# alter the training dataset for training
train_transform = transforms.Compose([
    transforms.RandomResizedCrop(INPUT_SHAPE, scale=(0.7, 1.0)),
    transforms.RandomHorizontalFlip(p=0.5),
    transforms.ColorJitter(brightness=0.2, contrast=0.2, saturation=0.2, hue=0.05),
    transforms.ToTensor(),
])

# keep validation unaltered
transform_val = transforms.Compose([
    transforms.Resize(INPUT_SHAPE),
    transforms.ToTensor(),
])

train_dataset = ImageNet20Dataset(txt_file=TRAIN_LIST, root_dir=IMAGE_ROOT, transform=train_transform)
train_loader = DataLoader(train_dataset, batch_size=BATCH_SIZE, shuffle=True)
print(f"Dataset loaded: {len(train_dataset)} images found.")


val_dataset = ImageNet20Dataset(txt_file=VAL_LIST, root_dir=VAL_IMAGE_ROOT, transform=transform_val)
val_loader = DataLoader(val_dataset, batch_size=BATCH_SIZE, shuffle=False)
print(f"Dataset loaded: {len(val_dataset)} images found.")

"""## Train Model

### Intialize model, criterion and optimizer
"""

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print(f"Using device: {device}")

model = NPUModel().to(device)
criterion = nn.CrossEntropyLoss()
optimizer = optim.SGD(model.parameters(), lr=LEARNING_RATE)

"""### Start training loop"""

# Validation
# Tracks Accuracy and Top-5 Accuracy
def validate(model, val_loader, criterion, device):
    model.eval()
    val_loss = 0.0
    correct = 0
    total = 0

    with torch.no_grad():
        for images, labels in val_loader:
            images, labels = images.to(device), labels.to(device)
            outputs = model(images)
            loss = criterion(outputs, labels)

            val_loss += loss.item()
            _, predicted = outputs.max(1)
            total += labels.size(0)
            correct += predicted.eq(labels).sum().item()

    avg_acc = 100. * correct / total
    avg_loss = val_loss / len(val_loader)
    return avg_loss, avg_acc

# Report Configuration

cfg = ReportConfig(
    run_name="imagenet20_mla100",
    out_dir="artifacts",
    num_classes=NUM_CLASSES,
    class_names=[
    "Water snake",
    "Roseate spoonbill",
    "Night Heron",
    "Limpkin",
    "Godwit",
    "Dog",
    "Hyena",
    "Monarch Butterfly",
    "Ram",
    "Impala",
    "Accoustic Guitar",
    "Sink",
    "Cabinet",
    "Hair Brooch",
    "Xylophone",
    "Nail",
    "Piggy Bank",
    "Pillow",
    "Tractor",
    "Monuments",
    ],
    top_k_examples=12,
    max_batches=0,          # set e.g. 20 for a faster dev pass
    make_pdf_each_epoch=True,
)

reporter = ModelReporter(cfg, gradcam_fn=None)

for epoch in range(NUM_EPOCHS):
    model.train()
    total_train, correct_train = 0, 0

    for i, (images, labels) in enumerate(train_loader):
        images, labels = images.to(device), labels.to(device)
        optimizer.zero_grad()
        outputs = model(images)
        loss = criterion(outputs, labels)
        loss.backward()
        optimizer.step()

        # Track Train Acc
        _, predicted = outputs.max(1)
        total_train += labels.size(0)
        correct_train += predicted.eq(labels).sum().item()

        if (i + 1) % 10 == 0:
            print(f"Epoch [{epoch+1}] Step [{i+1}/{len(train_loader)}] | Acc: {100.*correct_train/total_train:.2f}%")

    # --- Validation & Mismatch Analysis ---
    model.eval()
    val_correct, val_total = 0, 0
    mismatches = []

    with torch.no_grad():
        for images, labels in val_loader:
            images_dev = images.to(device)
            outputs = model(images_dev)
            _, predicted = outputs.max(1)

            val_total += labels.size(0)
            val_correct += predicted.eq(labels.to(device)).sum().item()

            # Collect 1 mismatch for the heatmap visualization
            mask = predicted.cpu() != labels
            if mask.any() and len(mismatches) < 3:
                idx = torch.where(mask)[0][0]
                mismatches.append({
                    'img': images[idx],
                    'true': labels[idx].item(),
                    'pred': predicted[idx].item()
                })

    print(f"\n>> Epoch {epoch+1} Summary: Val Acc: {100.*val_correct/val_total:.2f}% <<")

    # --- validation + PDF report ---
    pdf_path = reporter.build_epoch_report(
        model=model,
        val_loader=val_loader,
        device=device,
        epoch=epoch + 1,
        criterion=criterion,
        extra_meta={
            "learning_rate": LEARNING_RATE,
            "batch_size": BATCH_SIZE,
            "input_shape": list(INPUT_SHAPE),
        },
    )

    print(f"[report] wrote: {pdf_path}")

"""## Export Model to ONNX"""

model.eval()

# Move dummy input to same device as model
dummy_input = torch.randn(1, 3, 240, 240).to(device)
onnx_filename = "model.onnx"

torch.onnx.export(
    model,
    dummy_input,
    onnx_filename,
    verbose=False,
    input_names=['input'],
    output_names=['output'],
    dynamic_axes={'input': {0: 'batch_size'}, 'output': {0: 'batch_size'}}
)

print(f"Model successfully exported to {onnx_filename}")

# confirm onnx runtime classifies correctly
import numpy as np
from PIL import Image
import torchvision.transforms as transforms

NUM_IMAGES = 10   # set None for full validation

# -----------------------------
# Load validation list
# -----------------------------
samples = []
with open(VAL_LIST, "r") as f:
    for line in f:
        fname, label = line.strip().split()
        samples.append((fname, int(label)))

if NUM_IMAGES is not None:
    samples = samples[:NUM_IMAGES]
    print(f"num samples:{len(samples)}")

# -----------------------------
# Image preprocessing
# -----------------------------
def load_image(filename):

    print(f"filename: {filename}")

    folder = filename.split('_')[0]
    full_path = os.path.join(VAL_IMAGE_ROOT, filename)

    img = Image.open(full_path).convert("RGB")
    img = img.resize((240, 240), Image.BILINEAR)

    arr = np.array(img, dtype=np.float32) / 255.0  # ToTensor()
    arr = arr.transpose(2, 0, 1)                  # HWC → CHW
    arr = np.expand_dims(arr, axis=0)             # NCHW

    return arr.astype(np.float32)

test_images = []
labels = []

for fname, label in samples:
    test_images.append(load_image(fname))
    labels.append(label)

# onnx runtime test

ort_session = ort.InferenceSession(onnx_filename)
ort_inputs = {ort_session.get_inputs()[0].name: test_images[0]}
ort_outs = ort_session.run(None, ort_inputs)
print(ort_outs)

# [array([[-0.19135858, -0.23010466, -0.18045916, -0.05543918,  0.40322092,
#        -0.0212889 , -0.01825383, -0.3939799 , -0.11758958, -0.10948016,
#        -0.23098505,  0.15080309, -0.18484347,  0.3017688 , -0.2633909 ,
#         0.18919851,  0.2816175 ,  0.11519835,  0.05758833,  0.59133565]],
#      dtype=float32)]

# convert ort_outs to array
ort_outs_arr = np.array(ort_outs)
print(ort_outs_arr.shape)
# (1, 1, 20)

from collections import defaultdict, Counter

def read_list(path):
    items = []
    with open(path, "r") as f:
        for line in f:
            fname, lab = line.strip().split()
            items.append((fname, int(lab)))
    return items

def synset_from_fname(fname: str) -> str:
    # n01737021_10767.JPEG -> n01737021
    return fname.split("_")[0]

train_items = read_list(TRAIN_LIST)
val_items   = read_list(VAL_LIST)

def label_to_synsets(items):
    m = defaultdict(set)
    for fname, lab in items:
        m[lab].add(synset_from_fname(fname))
    return m

train_map = label_to_synsets(train_items)
val_map   = label_to_synsets(val_items)

print("TRAIN: unique labels:", sorted(train_map.keys()))
print("VAL:   unique labels:", sorted(val_map.keys()))

# Show mapping (label -> synset(s)) and flag weirdness (more than 1 synset per label)
print("\nLabel -> synset(s) from TRAIN list:")
for lab in sorted(train_map.keys()):
    syns = sorted(train_map[lab])
    flag = "  <-- ⚠ multiple synsets!" if len(syns) != 1 else ""
    print(f"{lab:>3}: {syns}{flag}")

print("\nLabel -> synset(s) from VAL list:")
for lab in sorted(val_map.keys()):
    syns = sorted(val_map[lab])
    flag = "  <-- ⚠ multiple synsets!" if len(syns) != 1 else ""
    print(f"{lab:>3}: {syns}{flag}")

# Hard consistency check between train and val
print("\n=== TRAIN vs VAL mapping differences ===")
all_labels = sorted(set(train_map.keys()) | set(val_map.keys()))
mismatch = False
for lab in all_labels:
    ts = sorted(train_map.get(lab, set()))
    vs = sorted(val_map.get(lab, set()))
    if ts != vs:
        mismatch = True
        print(f"Label {lab}: train={ts}  val={vs}")
if not mismatch:
    print("✅ Train/Val label->synset mapping matches for all labels.")

# Prefer train mapping as canonical
label_to_syn = {}
for lab in sorted(train_map.keys()):
    syns = sorted(train_map[lab])
    label_to_syn[lab] = syns[0] if syns else "UNKNOWN"

class_names = [label_to_syn[i] for i in range(NUM_CLASSES)]
print("class_names =", class_names)

cfg.class_names = class_names

import matplotlib.pyplot as plt
import numpy as np
from collections import defaultdict

def show_samples_by_class(ds, title, class_names=None, samples_per_class=3, num_classes=20, seed=0):
    """
    Shows `samples_per_class` samples for each class in order: 0..num_classes-1.
    Assumes ds[i] returns (img_tensor, label). If ds has `img_labels`, prints filename too.
    """
    rng = np.random.default_rng(seed)

    # Collect indices per label
    idxs_by_label = defaultdict(list)
    for i in range(len(ds)):
        item = ds[i]
        img, lab = item[0], item[1]
        idxs_by_label[int(lab)].append(i)

    # Plot grid: one row per class, N columns = samples_per_class
    rows = num_classes
    cols = samples_per_class
    plt.figure(figsize=(4 * cols, 2.8 * rows))
    plt.suptitle(title, y=0.995)

    plot_i = 1
    for lab in range(num_classes):
        idxs = idxs_by_label.get(lab, [])
        if len(idxs) == 0:
            # Empty row placeholder
            for c in range(cols):
                ax = plt.subplot(rows, cols, plot_i)
                ax.axis("off")
                if c == 0:
                    name = class_names[lab] if class_names and lab < len(class_names) else str(lab)
                    ax.set_title(f"class {lab} ({name})\nNO SAMPLES", fontsize=9)
                plot_i += 1
            continue

        # Choose samples_per_class indices (random if more available, else repeat fewer)
        if len(idxs) >= cols:
            chosen = rng.choice(idxs, size=cols, replace=False).tolist()
        else:
            chosen = idxs + rng.choice(idxs, size=(cols - len(idxs)), replace=True).tolist()

        for c, idx in enumerate(chosen):
            img, y = ds[idx]
            y = int(y)

            fname = None
            if hasattr(ds, "img_labels"):
                fname = ds.img_labels[idx][0]

            name = class_names[y] if class_names and y < len(class_names) else str(y)

            ax = plt.subplot(rows, cols, plot_i)
            ax.imshow(img.permute(1, 2, 0).clamp(0, 1))
            ax.axis("off")

            # Put label text once per row (first column), keep others clean
            if c == 0:
                ax.set_title(f"class {y} ({name})\n{fname}", fontsize=9)
            else:
                ax.set_title(f"{fname}", fontsize=8)

            plot_i += 1

    plt.tight_layout(rect=[0, 0, 1, 0.992])
    plt.show()


# Usage:
show_samples_by_class(
    train_dataset,
    "TRAIN samples grouped by class",
    class_names=class_names,          # ok if None
    samples_per_class=3,
    num_classes=NUM_CLASSES,
    seed=0
)

show_samples_by_class(
    val_dataset,
    "VAL samples grouped by class",
    class_names=class_names,
    samples_per_class=3,
    num_classes=NUM_CLASSES,
    seed=0
)

class_names=[
    "Water snake",
    "Roseate spoonbill",
    "Night Heron",
    "Limpkin",
    "Godwit",
    "Dog",
    "Hyena",
    "Monarch Butterfly",
    "Ram",
    "Impala",
    "Accoustic Guitar",
    "Sink",
    "Cabinet",
    "Hair Brooch",
    "Xylophone",
    "Nail",
    "Piggy Bank",
    "Pillow",
    "Tractor",
    "Monuments",
    ]