# -*- coding: utf-8 -*-
"""imagenet_mla100_ssl1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zLgMON4RiHMilnQrHA4zi8S1bR5QZ7-W

# ImageNet Classification for the MLA100 NPU chip

## Load Dataset
"""

from google.colab import drive
drive.mount('/content/drive')

!cp /content/drive/MyDrive/NPULab/spring-2026-data/imagenet_train20.txt imagenet_train20.txt
!cp /content/drive/MyDrive/NPULab/spring-2026-data/imagenet_val20.txt imagenet_val20.txt

# Text contains:
# file class_number
# file2 class_number2
# ...

!cp /content/drive/MyDrive/NPULab/spring-2026-data/imagenet_train20.zip imagenet_train20.zip

!cp /content/drive/MyDrive/NPULab/spring-2026-data/imagenet_val20.zip imagenet_val20.zip

!unzip -o -q imagenet_train20.zip
#   inflating: imagenet_train20a/n04346328/n04346328_2302.JPEG
#  inflating: imagenet_train20a/n04346328/n04346328_2842.JPEG

!unzip -o -q imagenet_val20.zip
# NOT NESTED UNDER SUB FOLDERS LIKE TRAINING
# ex., we get
# /imagenet_val20/n01737021_10767.JPEG

"""## Install Requirements"""

!pip -q install onnxscript onnxruntime

# Import required libraries
import torch
import torch.nn as nn
import torch.optim as optim
import torch.onnx
from torch.utils.data import Dataset, DataLoader
from torchvision import transforms
from PIL import Image
import os
import onnxscript
import onnxruntime as ort
import torch.nn.functional as F
from sklearn.metrics import classification_report, confusion_matrix
import numpy as np
import matplotlib.pyplot as plt
import torch
import torch.nn as nn
import torch.nn.functional as F
from torch.utils.data import Dataset
from torchvision import transforms
from PIL import Image
import os

"""## Prepare Dataset Loader"""

IMAGE_ROOT = 'imagenet_train20a'
TRAIN_LIST = 'imagenet_train20.txt'
VAL_IMAGE_ROOT = 'imagenet_val20'
VAL_LIST = 'imagenet_val20.txt'
BATCH_SIZE = 32
NUM_CLASSES = 20
INPUT_SHAPE = (240, 240)
NUM_EPOCHS = 10
LEARNING_RATE = 0.001

class BlockMasking:
    """Drops out random contiguous blocks of the image to force global reasoning."""
    def __init__(self, block_size=16, mask_ratio=0.4):
        self.block_size = block_size
        self.mask_ratio = mask_ratio

    def __call__(self, img):
        # img shape: [3, H, W]
        c, h, w = img.shape
        grid_h, grid_w = h // self.block_size, w // self.block_size

        # Create a randomized binary mask grid
        mask = torch.rand(1, grid_h, grid_w) < self.mask_ratio
        mask = mask.float()

        # Upsample the small grid to the full image size using nearest neighbor
        mask = F.interpolate(mask.unsqueeze(0), size=(h, w), mode='nearest').squeeze(0)

        # 1 means mask it (turn to 0), 0 means keep it.
        masked_img = img * (1 - mask)
        return masked_img

class ImageNet20Dataset(Dataset):
    def __init__(self, txt_file, root_dir, transform=None):
        self.img_labels = []
        self.root_dir = root_dir
        self.transform = transform
        self.masking = BlockMasking(block_size=16, mask_ratio=0.4) # 40% of image dropped

        with open(txt_file, 'r') as f:
            for line in f:
                parts = line.strip().split()
                if len(parts) >= 2:
                    self.img_labels.append((parts[0], int(parts[1])))

    def __len__(self):
        return len(self.img_labels)

    def __getitem__(self, idx):
        filename, label = self.img_labels[idx]
        path_flat = os.path.join(self.root_dir, filename)
        path_nested = os.path.join(self.root_dir, filename.split('_')[0], filename)
        full_path = path_flat if os.path.exists(path_flat) else path_nested

        try:
            image = Image.open(full_path).convert("RGB")
        except Exception:
            image = Image.new('RGB', (240, 240))

        # 1. Apply standard augmentations (Resize, ColorJitter, ToTensor)
        target_image = self.transform(image) if self.transform else image

        # 2. Generate the masked version for the input
        masked_image = self.masking(target_image)

        # Return both! Model sees masked_image, loss function uses target_image
        return masked_image, target_image, label

"""## Prepare Model

"""

class SpatialAttentionGate(nn.Module):
    """Generates a spatial heatmap and multiplies it with the feature map."""
    def __init__(self, channels):
        super().__init__()
        # Mini-decoder to find the most relevant spatial features
        self.att_conv = nn.Sequential(
            nn.Conv2d(channels, channels // 4, kernel_size=1, bias=False),
            nn.GroupNorm(4, channels // 4),
            nn.ReLU(inplace=True),
            nn.Conv2d(channels // 4, 1, kernel_size=1, bias=False),
            nn.Sigmoid() # Forces values between 0.0 and 1.0
        )

    def forward(self, x):
        attention_map = self.att_conv(x)
        # NPU Allowed Operation: Mul
        attended_features = x * attention_map
        return attended_features, attention_map

class NPUDecoder(nn.Module):
    """Scales the 15x15 latent space back to a 240x240 image."""
    def __init__(self, in_channels=256):
        super().__init__()
        # Using Nearest Upsample + Conv to avoid checkerboard artifacts (NPU allowed)
        self.decoder = nn.Sequential(
            nn.Upsample(scale_factor=2, mode='nearest'), # 15 -> 30
            nn.Conv2d(in_channels, 128, kernel_size=3, padding=1, bias=False),
            nn.GroupNorm(4, 128),
            nn.ReLU(inplace=True),

            nn.Upsample(scale_factor=2, mode='nearest'), # 30 -> 60
            nn.Conv2d(128, 64, kernel_size=3, padding=1, bias=False),
            nn.GroupNorm(4, 64),
            nn.ReLU(inplace=True),

            nn.Upsample(scale_factor=2, mode='nearest'), # 60 -> 120
            nn.Conv2d(64, 32, kernel_size=3, padding=1, bias=False),
            nn.GroupNorm(4, 32),
            nn.ReLU(inplace=True),

            nn.Upsample(scale_factor=2, mode='nearest'), # 120 -> 240
            nn.Conv2d(32, 3, kernel_size=3, padding=1, bias=True),
            nn.Sigmoid() # Images are normalized 0-1, so output must be 0-1
        )

    def forward(self, x):
        return self.decoder(x)

class NPUModel(nn.Module):
    def __init__(self, num_classes=20):
        super().__init__()

        # --- STAGE 1: STEM ---
        self.stem = nn.Sequential(
            nn.Conv2d(3, 32, kernel_size=3, stride=2, padding=1, bias=False),
            nn.GroupNorm(4, 32), # Replaced BatchNorm
            nn.ReLU(inplace=True)
        )

        # --- STAGE 2: MBCONV ---
        self.stage2 = nn.Sequential(
            nn.Conv2d(32, 128, kernel_size=3, stride=2, padding=1, bias=False),
            nn.GroupNorm(4, 128),
            nn.ReLU(inplace=True),
            nn.Conv2d(128, 64, kernel_size=1, stride=1, padding=0, bias=False),
            nn.GroupNorm(4, 64)
        )

        # --- STAGE 3: DOWNSAMPLE ---
        self.stage3 = nn.Sequential(
            nn.Conv2d(64, 128, kernel_size=3, stride=2, padding=1, bias=False),
            nn.GroupNorm(4, 128),
            nn.ReLU(inplace=True)
        )

        # --- STAGE 4: FEATURE REFINEMENT ---
        self.stage4 = nn.Sequential(
            nn.Conv2d(128, 256, kernel_size=1, stride=1, padding=0, bias=False),
            nn.GroupNorm(4, 256),
            nn.ReLU(inplace=True),
            nn.Conv2d(256, 256, kernel_size=3, stride=2, padding=1, groups=256, bias=False),
            nn.GroupNorm(4, 256),
            nn.ReLU(inplace=True)
        )

        # --- THE SPLIT ---
        self.attention_gate = SpatialAttentionGate(channels=256)
        self.decoder = NPUDecoder(in_channels=256)

        # --- CLASSIFIER HEAD ---
        self.classifier_conv = nn.Conv2d(256, num_classes, kernel_size=1, bias=True)
        self.global_pool = nn.AdaptiveAvgPool2d((1, 1))
        self.flatten = nn.Flatten() # NPU Allowed

    def forward(self, x, return_reconstruction=False):
        # Backbone Feature Extraction
        x = self.stem(x)
        x = self.stage2(x)
        x = self.stage3(x)
        features = self.stage4(x) # Shape: (B, 256, 15, 15)

        # 1. Attention Filtering
        attended_features, attention_map = self.attention_gate(features)

        # 2. Classification Branch (using filtered features)
        cls_out = self.classifier_conv(attended_features)
        cls_out = self.global_pool(cls_out)
        logits = self.flatten(cls_out)

        # During inference (ONNX export), we only care about the logits.
        if not return_reconstruction:
            return logits

        # 3. Reconstruction Branch (forcing the network to learn global context)
        # We decode from the *unfiltered* features so the encoder has to learn everything.
        reconstructed_img = self.decoder(features)

        return logits, reconstructed_img, attention_map

"""## Data Augmentations"""

# alter the training dataset for training
train_transform = transforms.Compose([
    transforms.RandomResizedCrop(INPUT_SHAPE, scale=(0.7, 1.0)),
    transforms.RandomHorizontalFlip(p=0.5),
    transforms.ColorJitter(brightness=0.2, contrast=0.2, saturation=0.2, hue=0.05),
    transforms.ToTensor(),
])

# keep validation unaltered
transform_val = transforms.Compose([
    transforms.Resize(INPUT_SHAPE),
    transforms.ToTensor(),
])

train_dataset = ImageNet20Dataset(txt_file=TRAIN_LIST, root_dir=IMAGE_ROOT, transform=train_transform)
train_loader = DataLoader(train_dataset, batch_size=BATCH_SIZE, shuffle=True)
print(f"Dataset loaded: {len(train_dataset)} images found.")


val_dataset = ImageNet20Dataset(txt_file=VAL_LIST, root_dir=VAL_IMAGE_ROOT, transform=transform_val)
val_loader = DataLoader(val_dataset, batch_size=BATCH_SIZE, shuffle=False)
print(f"Dataset loaded: {len(val_dataset)} images found.")

"""## Train Model

### Intialize model, criterion and optimizer
"""

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print(f"Using device: {device}")

model = NPUModel().to(device)
criterion = nn.CrossEntropyLoss()
#optimizer = optim.SGD(model.parameters(), lr=LEARNING_RATE)
optimizer = optim.Adam(model.parameters(), lr=LEARNING_RATE)

"""### Start training loop"""

# Validation
# Tracks Accuracy and Top-5 Accuracy
def validate(model, val_loader, criterion, device):
    model.eval()
    val_loss = 0.0
    correct = 0
    total = 0

    with torch.no_grad():
        for images, labels in val_loader:
            images, labels = images.to(device), labels.to(device)
            outputs = model(images)
            loss = criterion(outputs, labels)

            val_loss += loss.item()
            _, predicted = outputs.max(1)
            total += labels.size(0)
            correct += predicted.eq(labels).sum().item()

    avg_acc = 100. * correct / total
    avg_loss = val_loss / len(val_loader)
    return avg_loss, avg_acc

class_names=[
"Water snake",
"Roseate spoonbill",
"Night Heron",
"Limpkin",
"Godwit",
"Dog",
"Hyena",
"Monarch Butterfly",
"Ram",
"Impala",
"Accoustic Guitar",
"Sink",
"Cabinet",
"Hair Brooch",
"Xylophone",
"Nail",
"Piggy Bank",
"Pillow",
"Tractor",
"Monuments",
]

import matplotlib.pyplot as plt
import numpy as np

def visualize_reconstruction(masked, target, recon, attention, epoch):
    """Plots the first image in the batch to track learning progress."""
    # Move tensors to CPU and convert to HWC numpy arrays for plotting
    masked_img = masked[0].cpu().permute(1, 2, 0).numpy()
    target_img = target[0].cpu().permute(1, 2, 0).numpy()

    # Detach gradients before moving to CPU
    recon_img = recon[0].detach().cpu().permute(1, 2, 0).numpy()

    # Attention map is (1, H, W). We squeeze it to (H, W)
    att_map = attention[0, 0].detach().cpu().numpy()

    # Clip values to ensure they stay in the 0-1 range for matplotlib
    masked_img = np.clip(masked_img, 0, 1)
    target_img = np.clip(target_img, 0, 1)
    recon_img = np.clip(recon_img, 0, 1)

    fig, axes = plt.subplots(1, 4, figsize=(16, 4))

    axes[0].imshow(target_img)
    axes[0].set_title("Original Target")
    axes[0].axis("off")

    axes[1].imshow(masked_img)
    axes[1].set_title("Masked Input")
    axes[1].axis("off")

    axes[2].imshow(recon_img)
    axes[2].set_title("Model Reconstruction")
    axes[2].axis("off")

    # Use a heatmap colormap for the attention
    im = axes[3].imshow(att_map, cmap='jet')
    axes[3].set_title("Spatial Attention Map")
    axes[3].axis("off")
    fig.colorbar(im, ax=axes[3], fraction=0.046, pad=0.04)

    plt.suptitle(f"Epoch {epoch} Visualization", fontsize=14)
    plt.tight_layout()
    plt.show()

# Initialize your two loss functions
criterion_cls = nn.CrossEntropyLoss()
criterion_recon = nn.MSELoss()

# This hyperparameter controls how much the model cares about reconstructing the image
# vs predicting the class. 0.5 is a great starting point for MAE architectures.
RECON_WEIGHT = 0.5

for epoch in range(NUM_EPOCHS):
    model.train()
    total_train, correct_train = 0, 0

    # 1. Fix the Unpacking (Now expects 3 items from the masked dataloader)
    for i, (masked_images, target_images, labels) in enumerate(train_loader):
        masked_images = masked_images.to(device)
        target_images = target_images.to(device)
        labels = labels.to(device)

        optimizer.zero_grad()

        # 2. Forward Pass: Tell the model we need the reconstruction for training
        logits, reconstructed_img, attention_map = model(masked_images, return_reconstruction=True)

        # 3. Calculate the Dual Loss
        loss_cls = criterion_cls(logits, labels)
        loss_recon = criterion_recon(reconstructed_img, target_images)

        # Combine the losses so the gradients mix in the shared encoder
        loss = loss_cls + (RECON_WEIGHT * loss_recon)

        loss.backward()
        optimizer.step()

        # Track Train Acc (using the logits)
        _, predicted = logits.max(1)
        total_train += labels.size(0)
        correct_train += predicted.eq(labels).sum().item()

        if (i + 1) % 10 == 0:
            print(f"Epoch [{epoch+1}] Step [{i+1}/{len(train_loader)}] | "
                  f"Acc: {100.*correct_train/total_train:.2f}% | "
                  f"Cls Loss: {loss_cls.item():.4f} | Recon Loss: {loss_recon.item():.4f}")

    # --- Validation & Mismatch Analysis ---
    # Note: Assuming your val_loader still uses the ORIGINAL ImageNet20Dataset without masking.
    # Validation should always be done on clean, unmasked images.
    model.eval()
    val_correct, val_total = 0, 0
    mismatches = []

    visualize_reconstruction(masked_images, target_images, reconstructed_img, attention_map, epoch+1)

    # --- Validation & Mismatch Analysis ---
    model.eval()
    val_correct, val_total = 0, 0
    mismatches = []

    with torch.no_grad():
        # UNPACK 3 ITEMS: We ignore the masked_images for validation
        for masked_images, target_images, labels in val_loader:
            # We evaluate on the clean target_images
            target_images = target_images.to(device)
            labels = labels.to(device)

            # Forward Pass: return_reconstruction=False because we only care about accuracy
            logits = model(target_images, return_reconstruction=False)
            _, predicted = logits.max(1)

            val_total += labels.size(0)
            val_correct += predicted.eq(labels).sum().item()

            # Collect mismatches
            mask = predicted.cpu() != labels.cpu()
            if mask.any() and len(mismatches) < 3:
                idx = torch.where(mask)[0][0]
                mismatches.append({
                    'img': target_images[idx].cpu(),
                    'true': labels[idx].item(),
                    'pred': predicted[idx].item()
                })

    print(f"\n>> Epoch {epoch+1} Summary: Val Acc: {100.*val_correct/val_total:.2f}% <<\n")

"""## Export Model to ONNX"""

model.eval()

# Move dummy input to same device as model
dummy_input = torch.randn(1, 3, 240, 240).to(device)
onnx_filename = "model.onnx"

torch.onnx.export(
    model,
    dummy_input,
    onnx_filename,
    verbose=False,
    input_names=['input'],
    output_names=['output'],
    dynamic_axes={'input': {0: 'batch_size'}, 'output': {0: 'batch_size'}}
)

print(f"Model successfully exported to {onnx_filename}")

# confirm onnx runtime classifies correctly
import numpy as np
from PIL import Image
import torchvision.transforms as transforms

NUM_IMAGES = 10   # set None for full validation

# -----------------------------
# Load validation list
# -----------------------------
samples = []
with open(VAL_LIST, "r") as f:
    for line in f:
        fname, label = line.strip().split()
        samples.append((fname, int(label)))

if NUM_IMAGES is not None:
    samples = samples[:NUM_IMAGES]
    print(f"num samples:{len(samples)}")

# -----------------------------
# Image preprocessing
# -----------------------------
def load_image(filename):

    print(f"filename: {filename}")

    folder = filename.split('_')[0]
    full_path = os.path.join(VAL_IMAGE_ROOT, filename)

    img = Image.open(full_path).convert("RGB")
    img = img.resize((240, 240), Image.BILINEAR)

    arr = np.array(img, dtype=np.float32) / 255.0  # ToTensor()
    arr = arr.transpose(2, 0, 1)                  # HWC → CHW
    arr = np.expand_dims(arr, axis=0)             # NCHW

    return arr.astype(np.float32)

test_images = []
labels = []

for fname, label in samples:
    test_images.append(load_image(fname))
    labels.append(label)

# onnx runtime test

ort_session = ort.InferenceSession(onnx_filename)
ort_inputs = {ort_session.get_inputs()[0].name: test_images[0]}
ort_outs = ort_session.run(None, ort_inputs)
print(ort_outs)

# [array([[-0.19135858, -0.23010466, -0.18045916, -0.05543918,  0.40322092,
#        -0.0212889 , -0.01825383, -0.3939799 , -0.11758958, -0.10948016,
#        -0.23098505,  0.15080309, -0.18484347,  0.3017688 , -0.2633909 ,
#         0.18919851,  0.2816175 ,  0.11519835,  0.05758833,  0.59133565]],
#      dtype=float32)]

# convert ort_outs to array
ort_outs_arr = np.array(ort_outs)
print(ort_outs_arr.shape)
# (1, 1, 20)

from collections import defaultdict, Counter

def read_list(path):
    items = []
    with open(path, "r") as f:
        for line in f:
            fname, lab = line.strip().split()
            items.append((fname, int(lab)))
    return items

def synset_from_fname(fname: str) -> str:
    # n01737021_10767.JPEG -> n01737021
    return fname.split("_")[0]

train_items = read_list(TRAIN_LIST)
val_items   = read_list(VAL_LIST)

def label_to_synsets(items):
    m = defaultdict(set)
    for fname, lab in items:
        m[lab].add(synset_from_fname(fname))
    return m

train_map = label_to_synsets(train_items)
val_map   = label_to_synsets(val_items)

print("TRAIN: unique labels:", sorted(train_map.keys()))
print("VAL:   unique labels:", sorted(val_map.keys()))

# Show mapping (label -> synset(s)) and flag weirdness (more than 1 synset per label)
print("\nLabel -> synset(s) from TRAIN list:")
for lab in sorted(train_map.keys()):
    syns = sorted(train_map[lab])
    flag = "  <-- ⚠ multiple synsets!" if len(syns) != 1 else ""
    print(f"{lab:>3}: {syns}{flag}")

print("\nLabel -> synset(s) from VAL list:")
for lab in sorted(val_map.keys()):
    syns = sorted(val_map[lab])
    flag = "  <-- ⚠ multiple synsets!" if len(syns) != 1 else ""
    print(f"{lab:>3}: {syns}{flag}")

# Hard consistency check between train and val
print("\n=== TRAIN vs VAL mapping differences ===")
all_labels = sorted(set(train_map.keys()) | set(val_map.keys()))
mismatch = False
for lab in all_labels:
    ts = sorted(train_map.get(lab, set()))
    vs = sorted(val_map.get(lab, set()))
    if ts != vs:
        mismatch = True
        print(f"Label {lab}: train={ts}  val={vs}")
if not mismatch:
    print("✅ Train/Val label->synset mapping matches for all labels.")

# Prefer train mapping as canonical
label_to_syn = {}
for lab in sorted(train_map.keys()):
    syns = sorted(train_map[lab])
    label_to_syn[lab] = syns[0] if syns else "UNKNOWN"

class_names = [label_to_syn[i] for i in range(NUM_CLASSES)]
print("class_names =", class_names)

cfg.class_names = class_names

import matplotlib.pyplot as plt
import numpy as np
from collections import defaultdict

def show_samples_by_class(ds, title, class_names=None, samples_per_class=3, num_classes=20, seed=0):
    """
    Shows `samples_per_class` samples for each class in order: 0..num_classes-1.
    Assumes ds[i] returns (img_tensor, label). If ds has `img_labels`, prints filename too.
    """
    rng = np.random.default_rng(seed)

    # Collect indices per label
    idxs_by_label = defaultdict(list)
    for i in range(len(ds)):
        item = ds[i]
        img, lab = item[0], item[1]
        idxs_by_label[int(lab)].append(i)

    # Plot grid: one row per class, N columns = samples_per_class
    rows = num_classes
    cols = samples_per_class
    plt.figure(figsize=(4 * cols, 2.8 * rows))
    plt.suptitle(title, y=0.995)

    plot_i = 1
    for lab in range(num_classes):
        idxs = idxs_by_label.get(lab, [])
        if len(idxs) == 0:
            # Empty row placeholder
            for c in range(cols):
                ax = plt.subplot(rows, cols, plot_i)
                ax.axis("off")
                if c == 0:
                    name = class_names[lab] if class_names and lab < len(class_names) else str(lab)
                    ax.set_title(f"class {lab} ({name})\nNO SAMPLES", fontsize=9)
                plot_i += 1
            continue

        # Choose samples_per_class indices (random if more available, else repeat fewer)
        if len(idxs) >= cols:
            chosen = rng.choice(idxs, size=cols, replace=False).tolist()
        else:
            chosen = idxs + rng.choice(idxs, size=(cols - len(idxs)), replace=True).tolist()

        for c, idx in enumerate(chosen):
            img, y = ds[idx]
            y = int(y)

            fname = None
            if hasattr(ds, "img_labels"):
                fname = ds.img_labels[idx][0]

            name = class_names[y] if class_names and y < len(class_names) else str(y)

            ax = plt.subplot(rows, cols, plot_i)
            ax.imshow(img.permute(1, 2, 0).clamp(0, 1))
            ax.axis("off")

            # Put label text once per row (first column), keep others clean
            if c == 0:
                ax.set_title(f"class {y} ({name})\n{fname}", fontsize=9)
            else:
                ax.set_title(f"{fname}", fontsize=8)

            plot_i += 1

    plt.tight_layout(rect=[0, 0, 1, 0.992])
    plt.show()


# Usage:
show_samples_by_class(
    train_dataset,
    "TRAIN samples grouped by class",
    class_names=class_names,          # ok if None
    samples_per_class=3,
    num_classes=NUM_CLASSES,
    seed=0
)

show_samples_by_class(
    val_dataset,
    "VAL samples grouped by class",
    class_names=class_names,
    samples_per_class=3,
    num_classes=NUM_CLASSES,
    seed=0
)

class_names=[
    "Water snake",
    "Roseate spoonbill",
    "Night Heron",
    "Limpkin",
    "Godwit",
    "Dog",
    "Hyena",
    "Monarch Butterfly",
    "Ram",
    "Impala",
    "Accoustic Guitar",
    "Sink",
    "Cabinet",
    "Hair Brooch",
    "Xylophone",
    "Nail",
    "Piggy Bank",
    "Pillow",
    "Tractor",
    "Monuments",
    ]