# -*- coding: utf-8 -*-
"""imagenet-mla100_ssl1_runner.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KT7nA2tAMAYwOgaKFrkJO9EszYkJrKVq

# SETUP
"""

from google.colab import userdata
GITHUB_TOKEN = userdata.get('GITHUB_TOKEN')

from google.colab import drive
drive.mount('/content/drive')

import os
!git clone https://oauth2:{GITHUB_TOKEN}@github.com/bencejdanko/imagenet-classification-mobilint-mla-100

# ensure latest
os.chdir('/content/imagenet-classification-mobilint-mla-100')
!cd /content/imagenet-classification-mobilint-mla-100 && git pull

# copy over package
!cp -r /content/imagenet-classification-mobilint-mla-100/2026-02-20/imagenet_mla100_ssl2 imagenet_mla100_ssl2

import sys
sys.path.append('/content/imagenet_mla100_ssl2')

!pip -q install onnxscript onnxruntime

"""# IMPLEMENTATION

"""

# download all necessary data
import download

import train