# -*- coding: utf-8 -*-
"""imagenet-mla100

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1SQmeZHWq5q5Iy7GYF6nnJhxxi0E4t6Wj

# ImageNet Classification for the MLA100 NPU chip

## Load Dataset
"""

!cp /content/drive/MyDrive/NPULab/spring-2026-data/imagenet_train20.txt imagenet_train20.txt
!cp /content/drive/MyDrive/NPULab/spring-2026-data/imagenet_val20.txt imagenet_val20.txt

# Text contains:
# file class_number
# file2 class_number2
# ...

!cp /content/drive/MyDrive/NPULab/spring-2026-data/imagenet_train20.zip imagenet_train20.zip

!unzip -q imagenet_train20.zip
#   inflating: imagenet_train20a/n04346328/n04346328_2302.JPEG
#  inflating: imagenet_train20a/n04346328/n04346328_2842.JPEG

"""## Install Requirements"""

!pip -q install onnxscript

# Import required libraries
import torch
import torch.nn as nn
import torch.optim as optim
import torch.onnx
from torch.utils.data import Dataset, DataLoader
from torchvision import transforms
from PIL import Image
import os
import onnxscript

"""## Prepare Dataset Loader"""

IMAGE_ROOT = 'imagenet_train20a'
TRAIN_LIST = 'imagenet_train20.txt'
BATCH_SIZE = 32
NUM_CLASSES = 20
INPUT_SHAPE = (240, 240)
NUM_EPOCHS = 5
LEARNING_RATE = 0.01

class ImageNet20Dataset(Dataset):
    def __init__(self, txt_file, root_dir, transform=None):
        self.img_labels = []
        self.root_dir = root_dir
        self.transform = transform

        with open(txt_file, 'r') as f:
            for line in f:
                parts = line.strip().split()
                if len(parts) >= 2:
                    self.img_labels.append((parts[0], int(parts[1])))

    def __len__(self):
        return len(self.img_labels)

    def __getitem__(self, idx):
        filename, label = self.img_labels[idx]

        folder_name = filename.split('_')[0]

        full_path = os.path.join(self.root_dir, folder_name, filename)

        try:
            image = Image.open(full_path).convert("RGB")
        except Exception as e:
            print(f"Error loading {full_path}: {e}")
            image = Image.new('RGB', INPUT_SHAPE)

        if self.transform:
            image = self.transform(image)

        return image, label

"""## Prepare SimpleDNN"""

class SimpleDNN(nn.Module):
    def __init__(self):
        super(SimpleDNN, self).__init__()

        # We use Strided Convolutions (stride=2) instead of MaxPool
        # This reduces dimensions: 240 -> 120 -> 60 -> 30
        self.features = nn.Sequential(
            # Layer 1: 240x240 -> 120x120
            nn.Conv2d(3, 16, kernel_size=(3,3), stride=(2,2), padding=(1,1)),
            nn.ReLU(),

            # Layer 2: 120x120 -> 60x60
            nn.Conv2d(16, 32, kernel_size=(3,3), stride=(2,2), padding=(1,1)),
            nn.ReLU(),

            # Layer 3: 60x60 -> 30x30
            nn.Conv2d(32, 64, kernel_size=(3,3), stride=(2,2), padding=(1,1)),
            nn.ReLU()
        )

        # Calculate Flatten size: 64 channels * 30 width * 30 height
        self.flatten_size = 64 * 30 * 30

        # Final Classification Layer
        self.classifier = nn.Linear(self.flatten_size, NUM_CLASSES)

    def forward(self, x):
        x = self.features(x)
        x = x.view(x.size(0), -1) # Flatten
        x = self.classifier(x)
        return x

"""## Data Augmentations"""

transform = transforms.Compose([
    transforms.Resize(INPUT_SHAPE),
    transforms.ToTensor(),
])

try:
    train_dataset = ImageNet20Dataset(txt_file=TRAIN_LIST, root_dir=IMAGE_ROOT, transform=transform)
    train_loader = DataLoader(train_dataset, batch_size=BATCH_SIZE, shuffle=True)
    print(f"Dataset loaded: {len(train_dataset)} images found.")
except Exception as e:
    print(f"Dataset setup skipped. Error: {e}")
    train_loader = []

"""## Train Model

### Intialize model, criterion and optimizer
"""

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print(f"Using device: {device}")

model = SimpleDNN().to(device)
criterion = nn.CrossEntropyLoss()
optimizer = optim.SGD(model.parameters(), lr=LEARNING_RATE)

"""### Start training loop"""

if len(train_loader) > 0:
    for epoch in range(NUM_EPOCHS):
        model.train() # Set model to training mode
        running_loss = 0.0

        for i, (images, labels) in enumerate(train_loader):
            # Move data to GPU if available
            images, labels = images.to(device), labels.to(device)

            # Zero the parameter gradients
            optimizer.zero_grad()

            # Forward pass
            outputs = model(images)
            loss = criterion(outputs, labels)

            # Backward pass and optimize
            loss.backward()
            optimizer.step()

            running_loss += loss.item()

            # Print every 10 batches
            if (i + 1) % 10 == 0:
                print(f"Epoch [{epoch+1}/{NUM_EPOCHS}], Step [{i+1}/{len(train_loader)}], Loss: {loss.item():.4f}")

        epoch_loss = running_loss / len(train_loader)
        print(f"Epoch [{epoch+1}/{NUM_EPOCHS}] Finished. Average Loss: {epoch_loss:.4f}")
else:
    print("Skipping training loop (Dataset empty or not found).")

"""## Export Model to ONNX"""

model.eval()

# Move dummy input to same device as model
dummy_input = torch.randn(1, 3, 240, 240).to(device)
onnx_filename = "simple_imagenet20_model.onnx"

torch.onnx.export(
    model,
    dummy_input,
    onnx_filename,
    verbose=False,
    input_names=['input'],
    output_names=['output'],
    dynamic_axes={'input': {0: 'batch_size'}, 'output': {0: 'batch_size'}}
)

print(f"Model successfully exported to {onnx_filename}")

"""## Test Compilation

Using [https://github.com/bencejdanko/compiler-evaluation-server](https://github.com/bencejdanko/compiler-evaluation-server) as a compilation server.
"""

# Commented out IPython magic to ensure Python compatibility.
# %%bash
# NGROK_URL="https://3511-73-162-139-161.ngrok-free.app"
# 
# echo "$NGROK_URL/compile"
# 
# curl -X POST "$NGROK_URL/compile" \
#   -F "file=@simple_imagenet20_model.onnx" \
#   -F "output_name=custom_output.mxq"